First branch
tomerbod/survey-assignment pull request #1
Opened 2023-01-05 20:05 UTC by tomerbod

2023-01-17 15:47 UTC, taiebme commented on index.html
> +    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
Please use single script tag in order to run your app (you can keep the script tag for the chart.js).
Your app initialization should be done from within the code once the script is loaded

2023-01-17 21:08 UTC, taiebme commented on mocked.js
> +const mockData = () => {
Please store all relevant mock data as a `const` in separate file and import it from some util method which go over the array of data (for example) and insert it to the local storage instead of repeating yourself (DRY).

We've talked about it before, please use import/export in order to load some methods and don't rely on it already part of your code.

2023-01-17 21:13 UTC, taiebme commented on main.css
> +    font-size: 34px;
This comment is relevant for all your css files, I noticed that there are many common values you are using, such as colors, margins, etc.

in order to control the entire layout of your application in one place it is better to use css variables.
Please use css variables in order to store repeating values, you can read more about it [here](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)

2023-01-17 21:19 UTC, taiebme commented on classes/Result/openResultClass.js
> +    return answerContainer;
The `render` method is too long, please break it to several functions with single responsibility

2023-01-17 21:23 UTC, taiebme commented on pages/index.js
> +    }
Since your'e returning value from the if condition above, it is not relevant to use `else` in this case, please remove it

2023-01-17 21:24 UTC, taiebme commented on pages/index.js
> +  </tr>`;
Please store the html text in some `const` variable and put it in the beginning of the file

2023-01-17 21:33 UTC, taiebme commented on classes/router.js
> +              id: surveyId,
Why you are importing classes in this way ? 

Please import the relevant classes in `import` statements at the top of the page and use it instead of importing the files on demand which can delay the rendering of the page. 

Not so relevant but, if you are using async functions like here, please do it with `async` `await` syntax and not with `then` function callback.

2023-01-17 21:36 UTC, taiebme commented on classes/router.js
> +export default router;
Good job!

2023-01-17 21:38 UTC, taiebme commented on classes/storeManagerClass.js
> +class StoreManagerClass {
You can call it just `StoreManager`

2023-01-17 21:42 UTC, taiebme commented on pages/answer/answer.js
> +  }
The `renderPage` method is too long, please break it to several functions with single responsibility

2023-01-17 21:46 UTC, taiebme commented on utils.js
> +};
You are storing in this file `const` variables and therefore, you should call it `constants.js` and not `utils.js`, utils file should store several functions that are i common use in your application.

2023-01-17 21:47 UTC, taiebme commented on pages/results/results.js
> +          });
Please use enum instead hard coded value in the `switch case` options

2023-01-17 21:48 UTC, taiebme commented on pages/index.js
> +  }
The `renderPage` method is too long, please break it to several functions with single responsibility

2023-01-17 21:51 UTC, taiebme commented on pages/create/create.js
> +    return container;
The `renderPage` method is too long, please break it to several functions with single responsibility

2023-01-17 21:56 UTC, taiebme requested changes
Nice job, I added a few more comments, please review them

2023-01-18 13:18 UTC, tomerbod commented on index.html
> +    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
done

2023-01-18 13:18 UTC, tomerbod commented on mocked.js
> +const mockData = () => {
done

2023-01-18 13:18 UTC, tomerbod commented on main.css
> +    font-size: 34px;
done

2023-01-18 13:18 UTC, tomerbod commented on classes/Result/openResultClass.js
> +    return answerContainer;
done

2023-01-18 13:18 UTC, tomerbod commented on pages/index.js
> +    }
done

2023-01-18 13:19 UTC, tomerbod commented on pages/index.js
> +  </tr>`;
done

2023-01-18 13:19 UTC, tomerbod commented on classes/router.js
> +              id: surveyId,
done

2023-01-18 13:19 UTC, tomerbod commented on classes/storeManagerClass.js
> +class StoreManagerClass {
done

2023-01-18 13:19 UTC, tomerbod commented on pages/answer/answer.js
> +  }
done

2023-01-18 13:19 UTC, tomerbod commented on utils.js
> +};
done

2023-01-18 13:19 UTC, tomerbod commented on pages/results/results.js
> +          });
done

2023-01-18 13:19 UTC, tomerbod commented on pages/index.js
> +  }
done

2023-01-18 13:20 UTC, tomerbod commented on pages/create/create.js
> +    return container;
done

2023-07-17 03:21 UTC, closed without merging